# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 445)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(2500, 2000))
        MainWindow.setBaseSize(QtCore.QSize(700, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_daq = QtWidgets.QWidget()
        self.tab_daq.setObjectName("tab_daq")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_daq)
        self.gridLayout.setObjectName("gridLayout")
        self.label_duration = QtWidgets.QLabel(self.tab_daq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_duration.sizePolicy().hasHeightForWidth())
        self.label_duration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label_duration.setFont(font)
        self.label_duration.setObjectName("label_duration")
        self.gridLayout.addWidget(self.label_duration, 1, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.tab_daq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 5, 1, 1)
        self.pButton_start = QtWidgets.QPushButton(self.tab_daq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pButton_start.sizePolicy().hasHeightForWidth())
        self.pButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pButton_start.setFont(font)
        self.pButton_start.setAutoFillBackground(False)
        self.pButton_start.setObjectName("pButton_start")
        self.gridLayout.addWidget(self.pButton_start, 1, 0, 1, 1)
        self.pButton_stop = QtWidgets.QPushButton(self.tab_daq)
        self.pButton_stop.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pButton_stop.sizePolicy().hasHeightForWidth())
        self.pButton_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.pButton_stop.setFont(font)
        self.pButton_stop.setCheckable(False)
        self.pButton_stop.setObjectName("pButton_stop")
        self.gridLayout.addWidget(self.pButton_stop, 4, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.tab_daq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(100, 55))
        self.horizontalSlider.setSizeIncrement(QtCore.QSize(0, 0))
        self.horizontalSlider.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setMaximum(120)
        self.horizontalSlider.setPageStep(5)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setTickInterval(5)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 4, 3, 1, 3)
        self.label_session = QtWidgets.QLabel(self.tab_daq)
        self.label_session.setObjectName("label_session")
        self.gridLayout.addWidget(self.label_session, 0, 0, 1, 1)
        self.pButton_datesession = QtWidgets.QPushButton(self.tab_daq)
        self.pButton_datesession.setObjectName("pButton_datesession")
        self.gridLayout.addWidget(self.pButton_datesession, 0, 5, 1, 1)
        self.line_session = QtWidgets.QLineEdit(self.tab_daq)
        self.line_session.setObjectName("line_session")
        self.gridLayout.addWidget(self.line_session, 0, 2, 1, 3)
        self.tabWidget.addTab(self.tab_daq, "")
        self.tab_sensors = QtWidgets.QWidget()
        self.tab_sensors.setEnabled(True)
        self.tab_sensors.setObjectName("tab_sensors")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_sensors)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.vLayout_sensors_2 = QtWidgets.QVBoxLayout()
        self.vLayout_sensors_2.setObjectName("vLayout_sensors_2")
        self.pButthon_link = QtWidgets.QPushButton(self.tab_sensors)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pButthon_link.setFont(font)
        self.pButthon_link.setObjectName("pButthon_link")
        self.vLayout_sensors_2.addWidget(self.pButthon_link)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_sensors_2.addItem(spacerItem)
        self.pButton_calib = QtWidgets.QPushButton(self.tab_sensors)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pButton_calib.setFont(font)
        self.pButton_calib.setObjectName("pButton_calib")
        self.vLayout_sensors_2.addWidget(self.pButton_calib)
        self.gridLayout_3.addLayout(self.vLayout_sensors_2, 3, 9, 1, 1)
        self.vLayout_sensors_1 = QtWidgets.QVBoxLayout()
        self.vLayout_sensors_1.setObjectName("vLayout_sensors_1")
        self.treeWidget = QtWidgets.QTreeWidget(self.tab_sensors)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.vLayout_sensors_1.addWidget(self.treeWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_sensors_1.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.vLayout_sensors_1, 3, 8, 1, 1)
        self.vLayout_sensors_0 = QtWidgets.QVBoxLayout()
        self.vLayout_sensors_0.setObjectName("vLayout_sensors_0")
        self.pButton_scan = QtWidgets.QPushButton(self.tab_sensors)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pButton_scan.setFont(font)
        self.pButton_scan.setObjectName("pButton_scan")
        self.vLayout_sensors_0.addWidget(self.pButton_scan)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_sensors_0.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.vLayout_sensors_0, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sensors, "")
        self.tab_viz = QtWidgets.QWidget()
        self.tab_viz.setObjectName("tab_viz")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_viz)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pButton_load_viz = QtWidgets.QPushButton(self.tab_viz)
        self.pButton_load_viz.setMinimumSize(QtCore.QSize(50, 30))
        self.pButton_load_viz.setMaximumSize(QtCore.QSize(50, 30))
        self.pButton_load_viz.setObjectName("pButton_load_viz")
        self.gridLayout_5.addWidget(self.pButton_load_viz, 0, 0, 1, 1)
        self.hLayout_viz = QtWidgets.QHBoxLayout()
        self.hLayout_viz.setObjectName("hLayout_viz")
        self.cBox_method = QtWidgets.QComboBox(self.tab_viz)
        self.cBox_method.setObjectName("cBox_method")
        self.cBox_method.addItem("")
        self.cBox_method.addItem("")
        self.cBox_method.addItem("")
        self.cBox_method.addItem("")
        self.hLayout_viz.addWidget(self.cBox_method)
        self.cBox_data = QtWidgets.QComboBox(self.tab_viz)
        self.cBox_data.setMinimumSize(QtCore.QSize(70, 30))
        self.cBox_data.setMaximumSize(QtCore.QSize(100, 30))
        self.cBox_data.setObjectName("cBox_data")
        self.hLayout_viz.addWidget(self.cBox_data)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hLayout_viz.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.hLayout_viz, 0, 2, 1, 1)
        self.vLayout_viz = QtWidgets.QVBoxLayout()
        self.vLayout_viz.setObjectName("vLayout_viz")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vLayout_viz.addItem(spacerItem4)
        self.gridLayout_5.addLayout(self.vLayout_viz, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_viz, "")
        self.tab_process = QtWidgets.QWidget()
        self.tab_process.setObjectName("tab_process")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_process)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vL_process = QtWidgets.QVBoxLayout()
        self.vL_process.setObjectName("vL_process")
        self.pButton_load_process = QtWidgets.QPushButton(self.tab_process)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_load_process.sizePolicy().hasHeightForWidth())
        self.pButton_load_process.setSizePolicy(sizePolicy)
        self.pButton_load_process.setMinimumSize(QtCore.QSize(50, 30))
        self.pButton_load_process.setMaximumSize(QtCore.QSize(50, 30))
        self.pButton_load_process.setObjectName("pButton_load_process")
        self.vL_process.addWidget(self.pButton_load_process)
        self.gL_process = QtWidgets.QGridLayout()
        self.gL_process.setObjectName("gL_process")
        self.label_4 = QtWidgets.QLabel(self.tab_process)
        self.label_4.setObjectName("label_4")
        self.gL_process.addWidget(self.label_4, 0, 3, 1, 1)
        self.pB_imu2body = QtWidgets.QPushButton(self.tab_process)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.pB_imu2body.setFont(font)
        self.pB_imu2body.setIconSize(QtCore.QSize(16, 12))
        self.pB_imu2body.setObjectName("pB_imu2body")
        self.gL_process.addWidget(self.pB_imu2body, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_process)
        self.label_5.setObjectName("label_5")
        self.gL_process.addWidget(self.label_5, 0, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_process)
        self.label_6.setObjectName("label_6")
        self.gL_process.addWidget(self.label_6, 0, 1, 1, 1)
        self.lineEdit_z = QtWidgets.QLineEdit(self.tab_process)
        self.lineEdit_z.setObjectName("lineEdit_z")
        self.gL_process.addWidget(self.lineEdit_z, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_process)
        self.label_3.setObjectName("label_3")
        self.gL_process.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_x = QtWidgets.QLineEdit(self.tab_process)
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.gL_process.addWidget(self.lineEdit_x, 1, 2, 1, 1)
        self.lineEdit_y = QtWidgets.QLineEdit(self.tab_process)
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.gL_process.addWidget(self.lineEdit_y, 1, 3, 1, 1)
        self.vL_process.addLayout(self.gL_process)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vL_process.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.vL_process, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_process, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.horizontalSlider.valueChanged['int'].connect(self.label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GORDATA"))
        self.label_duration.setText(_translate("MainWindow", "Duration: "))
        self.label.setText(_translate("MainWindow", "0"))
        self.pButton_start.setToolTip(_translate("MainWindow", "\'Start collecting data\'"))
        self.pButton_start.setText(_translate("MainWindow", "Start"))
        self.pButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label_session.setText(_translate("MainWindow", "Session Name"))
        self.pButton_datesession.setText(_translate("MainWindow", "session << date"))
        self.line_session.setText(_translate("MainWindow", "unamed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_daq), _translate("MainWindow", "DAQ"))
        self.pButthon_link.setText(_translate("MainWindow", "Link"))
        self.pButton_calib.setText(_translate("MainWindow", "Calibrate"))
        self.pButton_scan.setText(_translate("MainWindow", "Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sensors), _translate("MainWindow", "Sensors"))
        self.pButton_load_viz.setText(_translate("MainWindow", "Load"))
        self.cBox_method.setItemText(0, _translate("MainWindow", "Time"))
        self.cBox_method.setItemText(1, _translate("MainWindow", "PSD"))
        self.cBox_method.setItemText(2, _translate("MainWindow", "STFT"))
        self.cBox_method.setItemText(3, _translate("MainWindow", "WSST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viz), _translate("MainWindow", "Viz"))
        self.pButton_load_process.setText(_translate("MainWindow", "Load"))
        self.label_4.setText(_translate("MainWindow", "Y"))
        self.pB_imu2body.setText(_translate("MainWindow", "IMU to Body"))
        self.label_5.setText(_translate("MainWindow", "Z"))
        self.label_6.setText(_translate("MainWindow", "CoM"))
        self.label_3.setText(_translate("MainWindow", "X"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_process), _translate("MainWindow", "Process"))

